# Generated by Django 4.0.1 on 2022-01-08 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('classes', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rollno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('english', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
                ('biology', models.IntegerField(blank=True, null=True)),
                ('rollno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studentinfo')),
            ],
        ),
    ]
